OfficeDev/microsoft-teams-apps-company-communicator

Deployment/azuredeploy.json
Create Azure Front Door resources and setup via the ARM template, when the custom domain mode is set to "Azure Front Door"
=> Include AFD setup in the ARM template

Deployment/azuredeploy.json, Source/Microsoft.Teams.Apps.CompanyCommunicator/Controllers/HealthController.cs
Add /health endpoint to the app
Reduce health probe frequency to every 255 seconds.
=> Add /health endpoint to the app

Source/Microsoft.Teams.Apps.CompanyCommunicator/Controllers/SentNotificationsController.cs, Source/Microsoft.Teams.Apps.CompanyCommunicator/Models/SentNotificationSummary.cs
- Add TotalMessageCount in SentNotificationSummary. So that UI can use it to replace the "Sending..."+spinner with "Sending... x/y" number of current number/total number of messages.
=> Add TotalMessageCount in SentNotificationSummary. 

Source/Microsoft.Teams.Apps.CompanyCommunicator/ClientApp/src/actions/index.ts, Source/Microsoft.Teams.Apps.CompanyCommunicator/ClientApp/src/components/Messages/messages.tsx
Change "Sending..."+spinner to "Sending... x/y" number of current number/total number of messages
=> Change "Sending..."+spinner to "Sending... x/y" number of current number/total number of messages

Source/Microsoft.Teams.Apps.CompanyCommunicator/Authentication/AuthenticationServiceCollectionExtensions.cs
- Add AudienceValidator in authentication.
=> Add AudienceValidator in authentication.

Source/Microsoft.Teams.Apps.CompanyCommunicator/ClientApp/src/components/NewMessage/newMessage.scss, Source/Microsoft.Teams.Apps.CompanyCommunicator/ClientApp/src/components/NewMessage/newMessage.tsx
check that URL for image and button.URL
=> check that URL for image and button.URL

Source/Microsoft.Teams.Apps.CompanyCommunicator/ClientApp/src/components/Messages/messages.scss, Source/Microsoft.Teams.Apps.CompanyCommunicator/ClientApp/src/components/Messages/messages.tsx
Make recipient numbers and Date timestamps semi-bold
=> Make recipient numbers and Date timestamps semi-bold

Source/Microsoft.Teams.Apps.CompanyCommunicator/ClientApp/src/apis/axiosJWTDecorator.ts
Add log of error when getAuthToken fails.
=> Add log of error when getAuthToken fails.

Source/Microsoft.Teams.Apps.CompanyCommunicator/ClientApp/src/components/DraftMessages/draftMessages.tsx, Source/Microsoft.Teams.Apps.CompanyCommunicator/ClientApp/src/components/Messages/messages.tsx
Fix Main tab - clicking the message multiple times quickly results in multiple Task Modules opening.
=> Fix Main tab - clicking the message multiple times quickly results in multiple Task Modules opening.

Source/Microsoft.Teams.Apps.CompanyCommunicator/ClientApp/src/App.scss
FE - move loading spinner on message Task Module to center
=> FE - move loading spinner on message Task Module to center

Source/Microsoft.Teams.Apps.CompanyCommunicator/ClientApp/src/App.scss, Source/Microsoft.Teams.Apps.CompanyCommunicator/ClientApp/src/components/TabContainer/tabContainer.scss
Polish main tab - message lists
=> Polish main tab - message lists

Source/Microsoft.Teams.Apps.CompanyCommunicator/Controllers/SentNotificationsController.cs, Source/Microsoft.Teams.Apps.CompanyCommunicator/Models/SentNotification.cs
- Return that "Sending started" date in the SendNotification model.
=> Return that "Sending started" date in the SendNotification model.

Source/Microsoft.Teams.Apps.CompanyCommunicator/ClientApp/src/actions/index.ts, Source/Microsoft.Teams.Apps.CompanyCommunicator/ClientApp/src/components/Messages/messages.tsx, Source/Microsoft.Teams.Apps.CompanyCommunicator/ClientApp/src/components/StatusTaskModule/statusTaskModule.tsx
Add time duration to status TM
=> Add time duration to status TM

Source/Microsoft.Teams.Apps.CompanyCommunicator/ClientApp/src/components/Messages/messages.tsx
Remove Extra space in "Sending... 0 of 100" string
=> Remove extra space in "Sending... 0 of 100" string

Source/Microsoft.Teams.Apps.CompanyCommunicator/ClientApp/src/App.scss, Source/Microsoft.Teams.Apps.CompanyCommunicator/ClientApp/src/components/TabContainer/tabContainer.scss
-lower card to align with input box;
-decrease whitespace in the middle 32 px; 
-hold width to 420 px
=> Polish card -lower card to align with input box; decrease whitespace in the middle 32 px; hold width to 420 px

Source/Microsoft.Teams.Apps.CompanyCommunicator/Bot/CompanyCommunicatorBot.cs
- Stop the bot from sending any echo response to users.
=> Stop the bot from sending any echo response to users.

Source/Microsoft.Teams.Apps.CompanyCommunicator/ClientApp/src/components/SendConfirmationTaskModule/sendConfirmationTaskModule.tsx
Alphabetize team names in Sending confirmation TM
=> Alphabetize team names in Sending confirmation TM

Source/Microsoft.Teams.Apps.CompanyCommunicator/ClientApp/src/components/config.tsx
=> remove website url

Source/Microsoft.Teams.Apps.CompanyCommunicator/NotificationDelivery/NotificationDelivery.cs
- Stop the "send all users" option from fetching any rosters.
=> Stop the “send all users” option from fetching any rosters.

Source/Microsoft.Teams.Apps.CompanyCommunicator.Common/Repositories/TeamData/TeamDataRepository.cs, Source/Microsoft.Teams.Apps.CompanyCommunicator/Controllers/SentNotificationsController.cs, Source/Microsoft.Teams.Apps.CompanyCommunicator/Models/SentNotification.cs
- Add audiences to the model to be shown in the Sent Status TM.
=> Add audiences to the model to be shown in the Sent Status TM.

Source/Microsoft.Teams.Apps.CompanyCommunicator/ClientApp/src/components/StatusTaskModule/statusTaskModule.tsx
Show audience selection in Sent Status TM
=> Show audience selection in Sent Status TM

Source/Microsoft.Teams.Apps.CompanyCommunicator/ClientApp/src/components/StatusTaskModule/statusTaskModule.tsx
=> bug fix for status TM

Source/Microsoft.Teams.Apps.CompanyCommunicator/ClientApp/src/App.scss
=> fix new message TM scroll bar

Source/Microsoft.Teams.Apps.CompanyCommunicator.Send.Func/CompanyCommunicatorDataFunction.cs, Source/Microsoft.Teams.Apps.CompanyCommunicator.Send.Func/CompanyCommunicatorSendFunction.cs
Changed how the configuration is built in order to fix extra handles issue
=> Changed how the configuration is built in order to fix extra handles issue

Source/Microsoft.Teams.Apps.CompanyCommunicator.Prep.Func/Export/Activities/UploadActivity.cs
Set UTF8 encoding for StreamWriter in CsvWriter. https://github.com/JoshClose/CsvHelper/issues/177#issuecomment-20854475
Fixed issue #260
=> Fixed encoding issue in csv files

Source/Microsoft.Teams.Apps.CompanyCommunicator.Data.Func/Microsoft.Teams.Apps.CompanyCommunicator.Data.Func.csproj, Source/Microsoft.Teams.Apps.CompanyCommunicator.Prep.Func/Export/Activities/UploadActivity.cs, Source/Microsoft.Teams.Apps.CompanyCommunicator.Prep.Func/Microsoft.Teams.Apps.CompanyCommunicator.Prep.Func.csproj, Source/Microsoft.Teams.Apps.CompanyCommunicator.Send.Func/Microsoft.Teams.Apps.CompanyCommunicator.Send.Func.csproj, Source/Microsoft.Teams.Apps.CompanyCommunicator/ClientApp/package-lock.json, Source/Microsoft.Teams.Apps.CompanyCommunicator/ClientApp/package.json, Source/Microsoft.Teams.Apps.CompanyCommunicator/ClientApp/src/components/OverFlow/draftMessageOverflow.tsx
- Update packages to address #241 
- Bump version number in package.json to 3.0.1
=> 3.0.1 release

Source/Microsoft.Teams.Apps.CompanyCommunicator.Common/Repositories/NotificationData/NotificationDataEntity.cs
This PR will support backward compatibility for messages. 
- Null handling for previous version messages.
=> Backward compatibility for groups

Deployment/deploy.ps1, Manifest/manifest_authors.json, Manifest/manifest_users.json, Source/CompanyCommunicator.Prep.Func/Startup.cs, Source/CompanyCommunicator/Bot/TeamsDataCapture.cs, Source/CompanyCommunicator/ClientApp/package-lock.json
- Update version number in manifests to 4.1.1
- Fix bug in #420 where it tries to get the member information for the bot, resulting for 404 Not Found errors
- Ensure Azure tables are created by prep function. This allows a fix for the issue reported in #420 by simply deleting the UserData table and restarting the prep Azure function.
- Update npm packages
=> Company Communicator v4.1.1

Manifest/manifest_authors.json, Manifest/manifest_users.json, Source/CompanyCommunicator/ClientApp/package-lock.json, Source/CompanyCommunicator/ClientApp/package.json
- Update manifest version to 4.1.2
- Update package.json version to 4.1.2
- Update npm packages
=> Company Communicator v4.1.2

Source/CompanyCommunicator.Common/Resources/Strings.ru-RU.resx, Source/CompanyCommunicator.Common/Resources/Strings.zh-CN.resx, Source/CompanyCommunicator.Common/Resources/Strings.zh-TW.resx, Source/CompanyCommunicator.Prep.Func/Export/Streams/DataStreamFacade.cs, Source/Test/CompanyCommunicator.Prep.Func.Test/Export/Streams/DataStreamFacadeTest.cs
- Support deleted users in export report
- localized strings
=> Support deleted users in export report

Manifest/manifest_authors.json, Manifest/manifest_users.json, Source/CompanyCommunicator/ClientApp/package-lock.json, Source/CompanyCommunicator/ClientApp/package.json
- Updating manifest and package.json to v4.1.3
=> Company Communicator v4.1.3

Manifest/manifest_authors.json, Manifest/manifest_users.json, Source/CompanyCommunicator.Common/Repositories/BaseRepository.cs, Source/CompanyCommunicator.Common/Repositories/NotificationData/NotificationDataRepository.cs, Source/CompanyCommunicator/ClientApp/package-lock.json, Source/CompanyCommunicator/ClientApp/package.json, Source/Test/CompanyCommunicator.Common.Test/Repositories/NotificationData/NotificationDataRepositoryTests.cs
- Limit the size of the error and warning messages columns to 1024 characters
- update package version
=> Company Communicator v4.1.5

Deployment/azuredeploy.json, Deployment/azuredeploywithcert.json, README.md, Wiki/Deployment-guide-certificate.md, Wiki/Deployment-guide-powershell.md, Wiki/Deployment-guide.md
- Update the documentation with latest version information.
- Set default hosting plan size to 2.
=> Company Communicator v5.0

README.md
Fixed the broken URL's in the Read Me file referring to migration guides.
=> Fix migration guide links in ReadMe file

Deployment/azuredeploywithcert.json
Both ARM templates should have the same Node version
In this PR the Node version update for azuredeploywithcert.json ARM template.
=> Node version update

Support/Check-AppRegistrations.ps1, Support/Check-GraphApp.ps1, Support/Start-ChatWithSpecifiedUser.ps1, Support/readme.md
I've added a support folder with troubleshooting scripts to help other having difficulties getting the application to work. Basically the scripts are there to make sure that the configuration is correct and/or needs updating.
=> Added support folder

Source/CompanyCommunicator/ClientApp/src/apis/apiDecorator.ts
Fixed the production issue related to app service authentication which is affecting users to send messages.
=> CC - Hot fix for app service authentication issue

Source/CompanyCommunicator/ClientApp/src/components/NewMessage/newMessage.tsx
Hotfix for app service sync failure issue
=> Hotfix - App Service Sync Issue 

Wiki/Data-stores.md
"succesfully" -> "successfully"
=> Typo fixes
